### ISSUE TITLE
HYST02 - Registro de nuevo trabajador - Lógica y Pruebas

### ISSUE THREAD

**Issue by jhorsax161616** [jhorsax161616/Grupo_1_Proyecto_CS#13]
Se estará implementando la lógica de la historia 2 y sus respectivas pruebas.

| Identificador | HYST02 |
| :---------- | :-------- |
| __Nombre (alias)__ | Registro de nuevo trabajador |
| __Descripción__ | Como empleador, deseo registrar a un trabajador, para actualizar el registro en la base de datos. |
| __Puntos de historia (Horas Ideaales)__ | 3 |
| __Criterios de aceptación__ | El software no deberá dejar campos vacíos en los nombres, al registrar el nombre del trabajador. |
|| El software no deberá permitir el ingreso de caracteres números, al registrar el nombre del trabajador. |
|| El software no deberá permitir ingresar símbolos, al registrar el nombre del trabajador |
|| El software no deberá permitir el ingreso de sueldo básico negativo al registrar el sueldo. |
|| El software no deberá permitir ingresar caracteres alfabéticos, al registrar el sueldo. |
|| El software no deberá permitir ingresar símbolos, al registrar el sueldo. |
|| El software solo deberá permitir como máximo hasta 35 caracteres, al registrar el nombre del trabajador. |
|| El software no deberá permitir el ingreso de dos nombres iguales al registrar el nombre del trabajador |

**Comment by JhimSebastian** [comment]
okok, yo trabajo el test
